air: 0
grass: 1
dirt: 2
granite: 3
basalt: 4
diorite: 5
marble: 6
obsidian: 7
sandstone: 8
sandstone_red: 9
water/water_still: 10
sand: 11
red_sand: 12
snow: 13
ice: 14
acacia_log: 15
birch_log: 16
cocoa_log: 17
coconut_log: 18
ebony_log: 19
mahagoni_log: 20
oak_log: 21
pine_log: 22
redwood_log: 23
spruce_log: 24
walnut_log: 25
willow_log: 26
acacia_wood: 27
birch_wood: 28
cocoa_wood: 29
coconut_wood: 30
ebony_wood: 31
mahagoni_wood: 32
oak_wood: 33
pine_wood: 34
redwood_wood: 35
spruce_wood: 36
walnut_wood: 37
willow_wood: 38
acacia_leaves: 39
birch_leaves: 40
cocoa_leaves: 41
coconut_leaves: 42
ebony_leaves: 43
mahagoni_leaves: 44
oak_leaves: 45
pine_leaves: 46
redwood_leaves: 47
spruce_leaves: 48
walnut_leaves: 49
willow_leaves: 50
grassbush: 51
heath: 52
aloe_vera: 53
nasturtium: 54
thingrass: 55
vine: 56
treemoss: 57
quarter: 58
ore_diamond: 59
ore_gold: 60
ore_silver: 61
granite_ore: 62
basalt_ore: 63
diorite_ore: 64
marble_ore: 65
obsidian_ore: 66
sandstone_ore: 67
sandstone_red_ore: 68
granite_brick: 69
basalt_brick: 70
diorite_brick: 71
marble_brick: 72
obsidian_brick: 73
sandstone_brick: 74
sandstone_red_brick: 75
clay_brick: 76
granite_stonebrick: 77
basalt_stonebrick: 78
diorite_stonebrick: 79
marble_stonebrick: 80
obsidian_stonebrick: 81
sandstone_stonebrick: 82
sandstone_red_stonebrick: 83
granite_smoothstone: 84
basalt_smoothstone: 85
diorite_smoothstone: 86
marble_smoothstone: 87
obsidian_smoothstone: 88
sandstone_smoothstone: 89
sandstone_red_smoothstone: 90
granite_stonepath: 91
basalt_stonepath: 92
diorite_stonepath: 93
marble_stonepath: 94
obsidian_stonepath: 95
sandstone_stonepath: 96
sandstone_red_stonepath: 97
granite_cobblestone: 98
basalt_cobblestone: 99
diorite_cobblestone: 100
marble_cobblestone: 101
obsidian_cobblestone: 102
sandstone_cobblestone: 103
sandstone_red_cobblestone: 104
granite_slab: 105
basalt_slab: 106
diorite_slab: 107
marble_slab: 108
obsidian_slab: 109
sandstone_slab: 110
sandstone_red_slab: 111
granite_stonepath_slab: 112
basalt_stonepath_slab: 113
diorite_stonepath_slab: 114
marble_stonepath_slab: 115
obsidian_stonepath_slab: 116
sandstone_stonepath_slab: 117
sandstone_red_stonepath_slab: 118
granite_cobblestone_slab: 119
basalt_cobblestone_slab: 120
diorite_cobblestone_slab: 121
marble_cobblestone_slab: 122
obsidian_cobblestone_slab: 123
sandstone_cobblestone_slab: 124
sandstone_red_cobblestone_slab: 125
granite_smoothstone_slab: 126
basalt_smoothstone_slab: 127
diorite_smoothstone_slab: 128
marble_smoothstone_slab: 129
obsidian_smoothstone_slab: 130
sandstone_smoothstone_slab: 131
sandstone_red_smoothstone_slab: 132
granite_stonebrick_slab: 133
basalt_stonebrick_slab: 134
diorite_stonebrick_slab: 135
marble_stonebrick_slab: 136
obsidian_stonebrick_slab: 137
sandstone_stonebrick_slab: 138
sandstone_red_stonebrick_slab: 139
granite_brick_slab: 140
basalt_brick_slab: 141
diorite_brick_slab: 142
marble_brick_slab: 143
obsidian_brick_slab: 144
sandstone_brick_slab: 145
sandstone_red_brick_slab: 146
clay_brick_slab: 147
acacia_log_slab: 148
birch_log_slab: 149
cocoa_log_slab: 150
coconut_log_slab: 151
ebony_log_slab: 152
mahagoni_log_slab: 153
oak_log_slab: 154
pine_log_slab: 155
redwood_log_slab: 156
spruce_log_slab: 157
walnut_log_slab: 158
willow_log_slab: 159
acacia_wood_slab: 160
birch_wood_slab: 161
cocoa_wood_slab: 162
coconut_wood_slab: 163
ebony_wood_slab: 164
mahagoni_wood_slab: 165
oak_wood_slab: 166
pine_wood_slab: 167
redwood_wood_slab: 168
spruce_wood_slab: 169
walnut_wood_slab: 170
willow_wood_slab: 171
granite_stairs: 172
basalt_stairs: 173
diorite_stairs: 174
marble_stairs: 175
obsidian_stairs: 176
sandstone_stairs: 177
sandstone_red_stairs: 178
granite_stonepath_stairs: 179
basalt_stonepath_stairs: 180
diorite_stonepath_stairs: 181
marble_stonepath_stairs: 182
obsidian_stonepath_stairs: 183
sandstone_stonepath_stairs: 184
sandstone_red_stonepath_stairs: 185
granite_cobblestone_stairs: 186
basalt_cobblestone_stairs: 187
diorite_cobblestone_stairs: 188
marble_cobblestone_stairs: 189
obsidian_cobblestone_stairs: 190
sandstone_cobblestone_stairs: 191
sandstone_red_cobblestone_stairs: 192
granite_smoothstone_stairs: 193
basalt_smoothstone_stairs: 194
diorite_smoothstone_stairs: 195
marble_smoothstone_stairs: 196
obsidian_smoothstone_stairs: 197
sandstone_smoothstone_stairs: 198
sandstone_red_smoothstone_stairs: 199
granite_stonebrick_stairs: 200
basalt_stonebrick_stairs: 201
diorite_stonebrick_stairs: 202
marble_stonebrick_stairs: 203
obsidian_stonebrick_stairs: 204
sandstone_stonebrick_stairs: 205
sandstone_red_stonebrick_stairs: 206
granite_brick_stairs: 207
basalt_brick_stairs: 208
diorite_brick_stairs: 209
marble_brick_stairs: 210
obsidian_brick_stairs: 211
sandstone_brick_stairs: 212
sandstone_red_brick_stairs: 213
clay_brick_stairs: 214
acacia_log_stairs: 215
birch_log_stairs: 216
cocoa_log_stairs: 217
coconut_log_stairs: 218
ebony_log_stairs: 219
mahagoni_log_stairs: 220
oak_log_stairs: 221
pine_log_stairs: 222
redwood_log_stairs: 223
spruce_log_stairs: 224
walnut_log_stairs: 225
willow_log_stairs: 226
acacia_wood_stairs: 227
birch_wood_stairs: 228
cocoa_wood_stairs: 229
coconut_wood_stairs: 230
ebony_wood_stairs: 231
mahagoni_wood_stairs: 232
oak_wood_stairs: 233
pine_wood_stairs: 234
redwood_wood_stairs: 235
spruce_wood_stairs: 236
walnut_wood_stairs: 237
willow_wood_stairs: 238
granite_wall: 239
basalt_wall: 240
diorite_wall: 241
marble_wall: 242
obsidian_wall: 243
sandstone_wall: 244
sandstone_red_wall: 245
granite_stonepath_wall: 246
basalt_stonepath_wall: 247
diorite_stonepath_wall: 248
marble_stonepath_wall: 249
obsidian_stonepath_wall: 250
sandstone_stonepath_wall: 251
sandstone_red_stonepath_wall: 252
granite_cobblestone_wall: 253
basalt_cobblestone_wall: 254
diorite_cobblestone_wall: 255
marble_cobblestone_wall: 256
obsidian_cobblestone_wall: 257
sandstone_cobblestone_wall: 258
sandstone_red_cobblestone_wall: 259
granite_smoothstone_wall: 260
basalt_smoothstone_wall: 261
diorite_smoothstone_wall: 262
marble_smoothstone_wall: 263
obsidian_smoothstone_wall: 264
sandstone_smoothstone_wall: 265
sandstone_red_smoothstone_wall: 266
granite_stonebrick_wall: 267
basalt_stonebrick_wall: 268
diorite_stonebrick_wall: 269
marble_stonebrick_wall: 270
obsidian_stonebrick_wall: 271
sandstone_stonebrick_wall: 272
sandstone_red_stonebrick_wall: 273
granite_brick_wall: 274
basalt_brick_wall: 275
diorite_brick_wall: 276
marble_brick_wall: 277
obsidian_brick_wall: 278
sandstone_brick_wall: 279
sandstone_red_brick_wall: 280
clay_brick_wall: 281
acacia_log_wall: 282
birch_log_wall: 283
cocoa_log_wall: 284
coconut_log_wall: 285
ebony_log_wall: 286
mahagoni_log_wall: 287
oak_log_wall: 288
pine_log_wall: 289
redwood_log_wall: 290
spruce_log_wall: 291
walnut_log_wall: 292
willow_log_wall: 293
acacia_wood_wall: 294
birch_wood_wall: 295
cocoa_wood_wall: 296
coconut_wood_wall: 297
ebony_wood_wall: 298
mahagoni_wood_wall: 299
oak_wood_wall: 300
pine_wood_wall: 301
redwood_wood_wall: 302
spruce_wood_wall: 303
walnut_wood_wall: 304
willow_wood_wall: 305
granite_fence: 306
basalt_fence: 307
diorite_fence: 308
marble_fence: 309
obsidian_fence: 310
sandstone_fence: 311
sandstone_red_fence: 312
granite_stonepath_fence: 313
basalt_stonepath_fence: 314
diorite_stonepath_fence: 315
marble_stonepath_fence: 316
obsidian_stonepath_fence: 317
sandstone_stonepath_fence: 318
sandstone_red_stonepath_fence: 319
granite_cobblestone_fence: 320
basalt_cobblestone_fence: 321
diorite_cobblestone_fence: 322
marble_cobblestone_fence: 323
obsidian_cobblestone_fence: 324
sandstone_cobblestone_fence: 325
sandstone_red_cobblestone_fence: 326
granite_smoothstone_fence: 327
basalt_smoothstone_fence: 328
diorite_smoothstone_fence: 329
marble_smoothstone_fence: 330
obsidian_smoothstone_fence: 331
sandstone_smoothstone_fence: 332
sandstone_red_smoothstone_fence: 333
granite_stonebrick_fence: 334
basalt_stonebrick_fence: 335
diorite_stonebrick_fence: 336
marble_stonebrick_fence: 337
obsidian_stonebrick_fence: 338
sandstone_stonebrick_fence: 339
sandstone_red_stonebrick_fence: 340
granite_brick_fence: 341
basalt_brick_fence: 342
diorite_brick_fence: 343
marble_brick_fence: 344
obsidian_brick_fence: 345
sandstone_brick_fence: 346
sandstone_red_brick_fence: 347
clay_brick_fence: 348
acacia_log_fence: 349
birch_log_fence: 350
cocoa_log_fence: 351
coconut_log_fence: 352
ebony_log_fence: 353
mahagoni_log_fence: 354
oak_log_fence: 355
pine_log_fence: 356
redwood_log_fence: 357
spruce_log_fence: 358
walnut_log_fence: 359
willow_log_fence: 360
acacia_wood_fence: 361
birch_wood_fence: 362
cocoa_wood_fence: 363
coconut_wood_fence: 364
ebony_wood_fence: 365
mahagoni_wood_fence: 366
oak_wood_fence: 367
pine_wood_fence: 368
redwood_wood_fence: 369
spruce_wood_fence: 370
walnut_wood_fence: 371
willow_wood_fence: 372
forget_me_not_black: 373
forget_me_not_blue: 374
compositae_camille: 375
compositae_milkspice: 376
compositae_pinkpanther: 377
compositae_tigerteeth: 378
violet: 379
rose: 380
poppy_blood: 381
poppy_grey: 382
poppy_blue: 383
oxmorina: 384
cup_black: 385
cup_blue: 386
cup_cyan: 387
cup_dark_yellow: 388
cup_orange: 389
cup_pink: 390
cup_red: 391
star_frost: 392
star_sundown: 393
dandelion: 394
lotus: 395
lavender: 396
tulip_red: 397
tulip_lilac: 398
tulip_darkblue: 399
tulip_orange: 400
tulip_pink: 401
tulip_white: 402
nomades: 403
sheeps_meal: 404
rhubarb: 405
fern1: 406
fern2: 407
fern3: 408
fern4: 409
double_heath: 410
tallgrass1: 411
tallgrass2: 412
cattail: 413
waterlily: 414
pad: 415
granite_carved: 416
basalt_carved: 417
diorite_carved: 418
marble_carved: 419
obsidian_carved: 420
sandstone_carved: 421
sandstone_red_carved: 422
granite_stonepath_carved: 423
basalt_stonepath_carved: 424
diorite_stonepath_carved: 425
marble_stonepath_carved: 426
obsidian_stonepath_carved: 427
sandstone_stonepath_carved: 428
sandstone_red_stonepath_carved: 429
granite_cobblestone_carved: 430
basalt_cobblestone_carved: 431
diorite_cobblestone_carved: 432
marble_cobblestone_carved: 433
obsidian_cobblestone_carved: 434
sandstone_cobblestone_carved: 435
sandstone_red_cobblestone_carved: 436
granite_smoothstone_carved: 437
basalt_smoothstone_carved: 438
diorite_smoothstone_carved: 439
marble_smoothstone_carved: 440
obsidian_smoothstone_carved: 441
sandstone_smoothstone_carved: 442
sandstone_red_smoothstone_carved: 443
granite_stonebrick_carved: 444
basalt_stonebrick_carved: 445
diorite_stonebrick_carved: 446
marble_stonebrick_carved: 447
obsidian_stonebrick_carved: 448
sandstone_stonebrick_carved: 449
sandstone_red_stonebrick_carved: 450
granite_brick_carved: 451
basalt_brick_carved: 452
diorite_brick_carved: 453
marble_brick_carved: 454
obsidian_brick_carved: 455
sandstone_brick_carved: 456
sandstone_red_brick_carved: 457
clay_brick_carved: 458
acacia_parquet: 459
birch_parquet: 460
cocoa_parquet: 461
coconut_parquet: 462
ebony_parquet: 463
mahagoni_parquet: 464
oak_parquet: 465
pine_parquet: 466
redwood_parquet: 467
spruce_parquet: 468
walnut_parquet: 469
willow_parquet: 470
gravel: 471
glass: 472
sand_ore: 473
red_sand_ore: 474
