pickaxe: 1
axe: 2
acacia_log: 3
birch_log: 4
cocoa_log: 5
coconut_log: 6
ebony_log: 7
mahagoni_log: 8
oak_log: 9
pine_log: 10
redwood_log: 11
spruce_log: 12
walnut_log: 13
willow_log: 14
acacia_plank: 15
birch_plank: 16
cocoa_plank: 17
coconut_plank: 18
ebony_plank: 19
mahagoni_plank: 20
oak_plank: 21
pine_plank: 22
redwood_plank: 23
spruce_plank: 24
walnut_plank: 25
willow_plank: 26
granite: 27
basalt: 28
